### ISSUE TITLE
Getting regeneratorRuntime is not defined using Create React App

### ISSUE THREAD

**Issue by chimon2000** [jxom/react-loads#18] opened 2019-04-01 20:14 UTC
![image](https://user-images.githubusercontent.com/6907797/55356537-f5604500-5498-11e9-9b53-a04ad6084238.png)

**Comment by jxom** [comment] 2019-04-02 06:15
Can you update to `7.0.2` and try again?

**Comment by jxom** [comment] 2019-04-04 01:11
Closing this - let me know if the issue is still happening post `7.0.2`.

**Closed by jxom** 2019-04-04 01:11 UTC
